### ISSUE TITLE
I need help to undestand how this realy works

### ISSUE THREAD

**Issue by brutalzinn** [GeirGrusom/WebShard#3]
is there any way for me to do the reverse process? Posting on a php page that my application is hosting on the route?

**Comment by GeirGrusom** [comment]
Sorry I didn't see this for some reason. I'm not entirely sure what you mean.

**Comment by GeirGrusom** [comment]
Hmm I guess you can accept either www-x-urlencoded or JSON and it should work like any other web server.

You biggest issue should be exposing this end point to the PHP page in some fashion

However I haven't worked on this library in quite some years. If you have any more specific questions related to the library itself I would be happy to answer them.
